workflow_details:
  name: Speedmap with Trend Analysis
  description: >-
    Multi-model trend analysis of mean walking speed over time.

er_client_name:
  data_source:
    name: "mep"

subject_obs:
  subject_group_name: "Elephants"

groupers:
  groupers:
    - index_name: subject_name

time_range:
  since: "2008-01-01T00:00:00Z"
  until: "2009-12-31T23:59:59Z"

trend_bucket:
  var: "%Y-%m-%d"

trend_model:
  model:
    model: "gam"
    spline_settings:
      degree_of_freedom: 3

chart_widget_title:
  var: Speed Trend Plot
