workflow_details:
  name: Speedmap with Trend Analysis
  description: >-
    Speed-classified elephant movement map and multi-model trend analysis of
    mean walking speed over time.

er_client_name:
  data_source:
    name: "EarthRanger"

subject_obs:
  subject_group_name: "Elephants"

groupers:
  groupers:
    - index_name: subject_name

time_range:
  since: "2008-01-01T00:00:00Z"
  until: "2009-12-31T23:59:59Z"

base_map_defs:
  base_maps:
    - url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
      opacity: 1.0
    - url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
      opacity: 0.5
      max_zoom: 17

trend_bucket:
  var: "%Y-%m"

trend_model:
  model:
    model: "gamm"
    spline_settings:
      degree_of_freedom: 3

map_widget_title:
  var: Subject Speed Map

chart_widget_title:
  var: Mean Speed Trend Chart
