# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details



# %% [markdown]
# # Speedmap
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import (
    map_values_with_unit as map_values_with_unit,
)
from ecoscope_workflows_core.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_speedmap_trend.tasks import fit_gamm_model as fit_gamm_model
from ecoscope_workflows_ext_speedmap_trend.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)
from ecoscope_workflows_ext_speedmap_trend.tasks import set_title_var as set_title_var

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Set Groupers

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

tracks_file_params = dict(
    var=...,
)

# %%
# call the task


tracks_file = (
    set_string_var.set_task_instance_id("tracks_file")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**tracks_file_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

load_subject_tracks_params = dict(
    layer=...,
)

# %%
# call the task


load_subject_tracks = (
    load_df.set_task_instance_id("load_subject_tracks")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        file_path=tracks_file, deserialize_json=False, **load_subject_tracks_params
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

rename_traj_columns_params = dict()

# %%
# call the task


rename_traj_columns = (
    map_columns.set_task_instance_id("rename_traj_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=load_subject_tracks,
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "subject__name": "subject_name",
            "subject__subject_subtype": "subject_subtype",
            "subject__sex": "subject_sex",
        },
        raise_if_not_found=False,
        **rename_traj_columns_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

traj_add_temporal_index_params = dict()

# %%
# call the task


traj_add_temporal_index = (
    add_temporal_index.set_task_instance_id("traj_add_temporal_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_traj_columns,
        time_col="segment_start",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **traj_add_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

classify_traj_speed_params = dict(
    label_options=...,
)

# %%
# call the task


classify_traj_speed = (
    apply_classification.set_task_instance_id("classify_traj_speed")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=traj_add_temporal_index,
        input_column_name="speed_kmhr",
        output_column_name="speed_bins",
        classification_options={
            "scheme": "equal_interval",
            "k": 6,
            "label_options": {"label_ranges": False, "label_decimals": 1},
        },
        **classify_traj_speed_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

split_subject_traj_groups_params = dict()

# %%
# call the task


split_subject_traj_groups = (
    split_groups.set_task_instance_id("split_subject_traj_groups")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=classify_traj_speed, groupers=groupers, **split_subject_traj_groups_params
    )
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

sort_traj_speed_params = dict()

# %%
# call the task


sort_traj_speed = (
    sort_values.set_task_instance_id("sort_traj_speed")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="speed_bins",
        ascending=True,
        na_position="last",
        **sort_traj_speed_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_subject_traj_groups)
)


# %% [markdown]
# ##

# %%
# parameters

colormap_traj_speed_params = dict()

# %%
# call the task


colormap_traj_speed = (
    apply_color_map.set_task_instance_id("colormap_traj_speed")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="speed_bins",
        output_column_name="speed_bins_colormap",
        colormap=["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"],
        **colormap_traj_speed_params,
    )
    .mapvalues(argnames=["df"], argvalues=sort_traj_speed)
)


# %% [markdown]
# ##

# %%
# parameters

speedmap_legend_with_unit_params = dict()

# %%
# call the task


speedmap_legend_with_unit = (
    map_values_with_unit.set_task_instance_id("speedmap_legend_with_unit")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="speed_bins",
        output_column_name="speed_bins_formatted",
        original_unit="km/h",
        new_unit="km/h",
        decimal_places=1,
        **speedmap_legend_with_unit_params,
    )
    .mapvalues(argnames=["df"], argvalues=colormap_traj_speed)
)


# %% [markdown]
# ##

# %%
# parameters

traj_map_layers_params = dict(
    zoom=...,
)

# %%
# call the task


traj_map_layers = (
    create_polyline_layer.set_task_instance_id("traj_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"color_column": "speed_bins_colormap"},
        legend={
            "label_column": "speed_bins_formatted",
            "color_column": "speed_bins_colormap",
        },
        tooltip_columns=["subject_name", "subject_subtype", "speed_kmhr"],
        **traj_map_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=speedmap_legend_with_unit)
)


# %% [markdown]
# ##

# %%
# parameters

traj_ecomap_params = dict(
    view_state=...,
    widget_id=...,
)

# %%
# call the task


traj_ecomap = (
    draw_ecomap.set_task_instance_id("traj_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=base_map_defs,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right"},
        static=False,
        title=None,
        max_zoom=20,
        **traj_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers"], argvalues=traj_map_layers)
)


# %% [markdown]
# ##

# %%
# parameters

ecomap_html_urls_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


ecomap_html_urls = (
    persist_text.set_task_instance_id("ecomap_html_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **ecomap_html_urls_params
    )
    .mapvalues(argnames=["text"], argvalues=traj_ecomap)
)


# %% [markdown]
# ##

# %%
# parameters

traj_add_month_index_params = dict()

# %%
# call the task


traj_add_month_index = (
    add_temporal_index.set_task_instance_id("traj_add_month_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        time_col="segment_start",
        groupers=[{"temporal_index": "%Y-%m"}],
        cast_to_datetime=True,
        format="mixed",
        **traj_add_month_index_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_subject_traj_groups)
)


# %% [markdown]
# ##

# %%
# parameters

speed_trends_params = dict()

# %%
# call the task


speed_trends = (
    summarize_df.set_task_instance_id("speed_trends")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        summary_params=[
            {
                "display_name": "mean_speed_kmhr",
                "aggregator": "mean",
                "column": "speed_kmhr",
            },
            {
                "display_name": "period_start",
                "aggregator": "min",
                "column": "segment_start",
                "decimal_places": None,
            },
        ],
        groupby_cols=["TemporalGrouper_%Y-%m"],
        reset_index=True,
        **speed_trends_params,
    )
    .mapvalues(argnames=["df"], argvalues=traj_add_month_index)
)


# %% [markdown]
# ##

# %%
# parameters

persist_speed_trend_data_params = dict(
    filename=...,
)

# %%
# call the task


persist_speed_trend_data = (
    persist_df_wrapper.set_task_instance_id("persist_speed_trend_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        sanitize=True,
        filename_prefix="speed_trends",
        filetypes=["parquet"],
        **persist_speed_trend_data_params,
    )
    .mapvalues(argnames=["df"], argvalues=speed_trends)
)


# %% [markdown]
# ##

# %%
# parameters

gamm_model_params = dict(
    metric=...,
    degree_of_freedom=...,
    degree=...,
    family=...,
)

# %%
# call the task


gamm_model = (
    fit_gamm_model.set_task_instance_id("gamm_model")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        time_column="period_start",
        value_column="mean_speed_kmhr",
        alpha=None,
        lower_bound=None,
        upper_bound=None,
        optimize_alpha=True,
        **gamm_model_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=speed_trends)
)


# %% [markdown]
# ##

# %%
# parameters

trend_predictions_params = dict()

# %%
# call the task


trend_predictions = (
    predict_gamm_trends.set_task_instance_id("trend_predictions")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_values=None, include_ci=True, **trend_predictions_params)
    .mapvalues(argnames=["model_params"], argvalues=gamm_model)
)


# %% [markdown]
# ##

# %%
# parameters

persist_trend_data_params = dict(
    filename=...,
)

# %%
# call the task


persist_trend_data = (
    persist_df_wrapper.set_task_instance_id("persist_trend_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        sanitize=True,
        filename_prefix="trend_predictions",
        filetypes=["parquet"],
        **persist_trend_data_params,
    )
    .mapvalues(argnames=["df"], argvalues=trend_predictions)
)


# %% [markdown]
# ## Trend Chart

# %%
# parameters

speed_trend_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


speed_trend_chart = (
    draw_historic_timeseries.set_task_instance_id("speed_trend_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        current_value_column="y",
        time_column="time",
        current_value_title="Observed Mean Speed",
        historic_min_column="ci_lower",
        historic_max_column="ci_upper",
        historic_mean_column="predicted",
        historic_mean_title="Trend Estimate",
        historic_band_title="Trend Confidence",
        layout_style={
            "xaxis": {"title": "Time"},
            "yaxis": {"title": "Mean Speed (km/h)"},
        },
        upper_lower_band_style={"mode": "lines", "line": {"color": "green"}},
        historic_mean_style=None,
        current_value_style=None,
        **speed_trend_chart_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=trend_predictions)
)


# %% [markdown]
# ##

# %%
# parameters

persist_speed_trend_chart_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_speed_trend_chart = (
    persist_text.set_task_instance_id("persist_speed_trend_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_speed_trend_chart_params,
    )
    .mapvalues(argnames=["text"], argvalues=speed_trend_chart)
)


# %% [markdown]
# ##

# %%
# parameters

map_widget_title_params = dict(
    title=...,
)

# %%
# call the task


map_widget_title = (
    set_title_var.set_task_instance_id("map_widget_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**map_widget_title_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

chart_widget_title_params = dict(
    title=...,
)

# %%
# call the task


chart_widget_title = (
    set_title_var.set_task_instance_id("chart_widget_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**chart_widget_title_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

speed_map_widget_params = dict()

# %%
# call the task


speed_map_widget = (
    create_map_widget_single_view.set_task_instance_id("speed_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=map_widget_title, **speed_map_widget_params)
    .map(argnames=["view", "data"], argvalues=ecomap_html_urls)
)


# %% [markdown]
# ##

# %%
# parameters

grouped_speed_map_params = dict()

# %%
# call the task


grouped_speed_map = (
    merge_widget_views.set_task_instance_id("grouped_speed_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=speed_map_widget, **grouped_speed_map_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

speed_trend_widget_params = dict()

# %%
# call the task


speed_trend_widget = (
    create_plot_widget_single_view.set_task_instance_id("speed_trend_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=chart_widget_title, **speed_trend_widget_params)
    .map(argnames=["view", "data"], argvalues=persist_speed_trend_chart)
)


# %% [markdown]
# ##

# %%
# parameters

grouped_speed_trend_params = dict()

# %%
# call the task


grouped_speed_trend = (
    merge_widget_views.set_task_instance_id("grouped_speed_trend")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=speed_trend_widget, **grouped_speed_trend_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

speedmap_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


speedmap_dashboard = (
    gather_dashboard.set_task_instance_id("speedmap_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        time_range=time_range,
        widgets=[grouped_speed_map, grouped_speed_trend],
        groupers=groupers,
        **speedmap_dashboard_params,
    )
    .call()
)
