# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details



# %% [markdown]
# # Speedmap
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_path_layer as create_path_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_spatial_features_group as get_spatial_features_group,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    add_spatial_index as add_spatial_index,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    extract_spatial_grouper_feature_group_names as extract_spatial_grouper_feature_group_names,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    resolve_spatial_feature_groups_for_spatial_groupers as resolve_spatial_feature_groups_for_spatial_groupers,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    set_title_var as set_title_var,
)

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Extract Timezone Selection

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

subject_obs_params = dict(
    subject_group_name=...,
)

# %%
# call the task


subject_obs = (
    get_subjectgroup_observations.set_task_instance_id("subject_obs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        raise_on_empty=False,
        include_details=False,
        include_subjectsource_details=False,
        filter="clean",
        **subject_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Convert to timezone

# %%
# parameters

convert_to_user_timezone_params = dict()

# %%
# call the task


convert_to_user_timezone = (
    convert_values_to_timezone.set_task_instance_id("convert_to_user_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=subject_obs,
        timezone=get_timezone,
        columns=["fixtime"],
        **convert_to_user_timezone_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

spatial_group_ids_params = dict()

# %%
# call the task


spatial_group_ids = (
    extract_spatial_grouper_feature_group_names.set_task_instance_id(
        "spatial_group_ids"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(groupers=groupers, **spatial_group_ids_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

fetch_spatial_feature_groups_params = dict()

# %%
# call the task


fetch_spatial_feature_groups = (
    get_spatial_features_group.set_task_instance_id("fetch_spatial_feature_groups")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(client=er_client_name, **fetch_spatial_feature_groups_params)
    .map(argnames=["spatial_features_group_name"], argvalues=spatial_group_ids)
)


# %% [markdown]
# ##

# %%
# parameters

resolved_groupers_params = dict()

# %%
# call the task


resolved_groupers = (
    resolve_spatial_feature_groups_for_spatial_groupers.set_task_instance_id(
        "resolved_groupers"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupers=groupers,
        spatial_feature_groups=fetch_spatial_feature_groups,
        **resolved_groupers_params,
    )
    .call()
)


# %% [markdown]
# ## Transform Observations to Relocations

# %%
# parameters

subject_reloc_params = dict()

# %%
# call the task


subject_reloc = (
    process_relocations.set_task_instance_id("subject_reloc")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        observations=convert_to_user_timezone,
        relocs_columns=[
            "groupby_col",
            "fixtime",
            "junk_status",
            "geometry",
            "extra__subject__name",
            "extra__subject__subject_subtype",
            "extra__subject__sex",
        ],
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **subject_reloc_params,
    )
    .call()
)


# %% [markdown]
# ## Convert Relocations to Trajectory

# %%
# parameters

subject_traj_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


subject_traj = (
    relocations_to_trajectory.set_task_instance_id("subject_traj")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(relocations=subject_reloc, **subject_traj_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

traj_add_temporal_index_params = dict()

# %%
# call the task


traj_add_temporal_index = (
    add_temporal_index.set_task_instance_id("traj_add_temporal_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=subject_traj,
        time_col="segment_start",
        groupers=resolved_groupers,
        cast_to_datetime=True,
        format="mixed",
        **traj_add_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

traj_add_spatial_index_params = dict()

# %%
# call the task


traj_add_spatial_index = (
    add_spatial_index.set_task_instance_id("traj_add_spatial_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=traj_add_temporal_index,
        groupers=resolved_groupers,
        **traj_add_spatial_index_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

rename_traj_columns_params = dict()

# %%
# call the task


rename_traj_columns = (
    map_columns.set_task_instance_id("rename_traj_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=traj_add_spatial_index,
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "extra__name": "subject_name",
            "extra__subject_subtype": "subject_subtype",
            "extra__sex": "subject_sex",
        },
        raise_if_not_found=True,
        **rename_traj_columns_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

classify_traj_speed_params = dict()

# %%
# call the task


classify_traj_speed = (
    apply_classification.set_task_instance_id("classify_traj_speed")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_traj_columns,
        input_column_name="speed_kmhr",
        output_column_name="speed_bins",
        classification_options={"scheme": "equal_interval", "k": 6},
        label_options={
            "label_ranges": True,
            "label_decimals": 1,
            "label_suffix": " km/h",
        },
        **classify_traj_speed_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

split_subject_traj_groups_params = dict()

# %%
# call the task


split_subject_traj_groups = (
    split_groups.set_task_instance_id("split_subject_traj_groups")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=classify_traj_speed,
        groupers=resolved_groupers,
        **split_subject_traj_groups_params,
    )
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps_pydeck.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

sort_traj_speed_params = dict()

# %%
# call the task


sort_traj_speed = (
    sort_values.set_task_instance_id("sort_traj_speed")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="speed_bins",
        ascending=True,
        na_position="last",
        **sort_traj_speed_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_subject_traj_groups)
)


# %% [markdown]
# ##

# %%
# parameters

colormap_traj_speed_params = dict()

# %%
# call the task


colormap_traj_speed = (
    apply_color_map.set_task_instance_id("colormap_traj_speed")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="speed_bins",
        output_column_name="speed_bins_colormap",
        colormap=["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"],
        **colormap_traj_speed_params,
    )
    .mapvalues(argnames=["df"], argvalues=sort_traj_speed)
)


# %% [markdown]
# ##

# %%
# parameters

traj_map_layers_params = dict()

# %%
# call the task


traj_map_layers = (
    create_path_layer.set_task_instance_id("traj_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"get_color": "speed_bins_colormap"},
        legend={
            "title": "Speed",
            "label_column": "speed_bins",
            "color_column": "speed_bins_colormap",
        },
        **traj_map_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=colormap_traj_speed)
)


# %% [markdown]
# ##

# %%
# parameters

traj_ecomap_params = dict(
    widget_id=...,
)

# %%
# call the task


traj_ecomap = (
    draw_map.set_task_instance_id("traj_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=base_map_defs,
        legend_style={"placement": "bottom-right"},
        static=False,
        title=None,
        max_zoom=20,
        view_state=None,
        **traj_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers"], argvalues=traj_map_layers)
)


# %% [markdown]
# ##

# %%
# parameters

ecomap_html_urls_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


ecomap_html_urls = (
    persist_text.set_task_instance_id("ecomap_html_urls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **ecomap_html_urls_params
    )
    .mapvalues(argnames=["text"], argvalues=traj_ecomap)
)


# %% [markdown]
# ##

# %%
# parameters

traj_add_month_index_params = dict()

# %%
# call the task


traj_add_month_index = (
    add_temporal_index.set_task_instance_id("traj_add_month_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        time_col="segment_start",
        groupers=[{"temporal_index": "%Y-%m"}],
        cast_to_datetime=True,
        format="mixed",
        **traj_add_month_index_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_subject_traj_groups)
)


# %% [markdown]
# ##

# %%
# parameters

speed_trends_params = dict()

# %%
# call the task


speed_trends = (
    summarize_df.set_task_instance_id("speed_trends")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        summary_params=[
            {
                "display_name": "mean_speed_kmhr",
                "aggregator": "mean",
                "column": "speed_kmhr",
            },
            {
                "display_name": "period_start",
                "aggregator": "min",
                "column": "segment_start",
                "decimal_places": None,
            },
        ],
        groupby_cols=["TemporalGrouper_%Y-%m"],
        reset_index=True,
        **speed_trends_params,
    )
    .mapvalues(argnames=["df"], argvalues=traj_add_month_index)
)


# %% [markdown]
# ##

# %%
# parameters

persist_speed_trend_data_params = dict(
    filename=...,
)

# %%
# call the task


persist_speed_trend_data = (
    persist_df_wrapper.set_task_instance_id("persist_speed_trend_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        sanitize=True,
        filename_prefix="speed_trends",
        filetypes=["parquet"],
        **persist_speed_trend_data_params,
    )
    .mapvalues(argnames=["df"], argvalues=speed_trends)
)


# %% [markdown]
# ##

# %%
# parameters

gamm_model_params = dict(
    metric=...,
    degree_of_freedom=...,
    degree=...,
    family=...,
)

# %%
# call the task


gamm_model = (
    fit_gamm_model.set_task_instance_id("gamm_model")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        time_column="period_start",
        value_column="mean_speed_kmhr",
        lower_bound=None,
        upper_bound=None,
        optimize_alpha=False,
        alpha=1.0,
        **gamm_model_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=speed_trends)
)


# %% [markdown]
# ##

# %%
# parameters

trend_predictions_params = dict()

# %%
# call the task


trend_predictions = (
    predict_gamm_trends.set_task_instance_id("trend_predictions")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_values=None, include_ci=True, **trend_predictions_params)
    .mapvalues(argnames=["model_params"], argvalues=gamm_model)
)


# %% [markdown]
# ##

# %%
# parameters

trend_time_cast_params = dict()

# %%
# call the task


trend_time_cast = (
    add_temporal_index.set_task_instance_id("trend_time_cast")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupers={},
        time_col="time",
        cast_to_datetime=True,
        format="mixed",
        **trend_time_cast_params,
    )
    .mapvalues(argnames=["df"], argvalues=trend_predictions)
)


# %% [markdown]
# ##

# %%
# parameters

persist_trend_data_params = dict(
    filename=...,
)

# %%
# call the task


persist_trend_data = (
    persist_df_wrapper.set_task_instance_id("persist_trend_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        sanitize=True,
        filename_prefix="trend_predictions",
        filetypes=["parquet"],
        **persist_trend_data_params,
    )
    .mapvalues(argnames=["df"], argvalues=trend_time_cast)
)


# %% [markdown]
# ## Trend Chart

# %%
# parameters

speed_trend_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


speed_trend_chart = (
    draw_historic_timeseries.set_task_instance_id("speed_trend_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        current_value_column="y",
        time_column="time",
        current_value_title="Observed Mean Speed",
        historic_min_column="ci_lower",
        historic_max_column="ci_upper",
        historic_mean_column="predicted",
        historic_mean_title="Trend Estimate",
        historic_band_title="Trend Confidence",
        layout_style={
            "xaxis": {"title": "Time"},
            "yaxis": {"title": "Mean Speed (km/h)"},
        },
        upper_lower_band_style={"mode": "lines", "line": {"color": "green"}},
        historic_mean_style=None,
        current_value_style=None,
        **speed_trend_chart_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=trend_time_cast)
)


# %% [markdown]
# ##

# %%
# parameters

persist_speed_trend_chart_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_speed_trend_chart = (
    persist_text.set_task_instance_id("persist_speed_trend_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_speed_trend_chart_params,
    )
    .mapvalues(argnames=["text"], argvalues=speed_trend_chart)
)


# %% [markdown]
# ##

# %%
# parameters

map_widget_title_params = dict(
    title=...,
)

# %%
# call the task


map_widget_title = (
    set_title_var.set_task_instance_id("map_widget_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**map_widget_title_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

chart_widget_title_params = dict(
    title=...,
)

# %%
# call the task


chart_widget_title = (
    set_title_var.set_task_instance_id("chart_widget_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**chart_widget_title_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

speed_map_widget_params = dict()

# %%
# call the task


speed_map_widget = (
    create_map_widget_single_view.set_task_instance_id("speed_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=map_widget_title, **speed_map_widget_params)
    .map(argnames=["view", "data"], argvalues=ecomap_html_urls)
)


# %% [markdown]
# ##

# %%
# parameters

grouped_speed_map_params = dict()

# %%
# call the task


grouped_speed_map = (
    merge_widget_views.set_task_instance_id("grouped_speed_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=speed_map_widget, **grouped_speed_map_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

speed_trend_widget_params = dict()

# %%
# call the task


speed_trend_widget = (
    create_plot_widget_single_view.set_task_instance_id("speed_trend_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=chart_widget_title, **speed_trend_widget_params)
    .map(argnames=["view", "data"], argvalues=persist_speed_trend_chart)
)


# %% [markdown]
# ##

# %%
# parameters

grouped_speed_trend_params = dict()

# %%
# call the task


grouped_speed_trend = (
    merge_widget_views.set_task_instance_id("grouped_speed_trend")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=speed_trend_widget, **grouped_speed_trend_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

speedmap_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


speedmap_dashboard = (
    gather_dashboard.set_task_instance_id("speedmap_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        time_range=time_range,
        widgets=[grouped_speed_map, grouped_speed_trend],
        groupers=resolved_groupers,
        **speedmap_dashboard_params,
    )
    .call()
)
