# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_subjectgroup_observations = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    extract_spatial_grouper_feature_group_names as extract_spatial_grouper_feature_group_names,
)

get_spatial_features_group = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import fit_trend_model as fit_trend_model
from ecoscope.platform.tasks.analysis import (
    get_trend_model_fit_summary as get_trend_model_fit_summary,
)
from ecoscope.platform.tasks.analysis import predict_trend_model as predict_trend_model
from ecoscope.platform.tasks.analysis import set_trend_model as set_trend_model
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.analysis._trend_analysis import (
    is_gamm_trend_model as is_gamm_trend_model,
)
from ecoscope.platform.tasks.analysis._trend_analysis import (
    is_not_gamm_trend_model as is_not_gamm_trend_model,
)
from ecoscope.platform.tasks.config import concat_string_vars as concat_string_vars
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.groupby import (
    groupbykey_passthrough_skip as groupbykey_passthrough_skip,
)
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_df_wrapper as persist_df_wrapper
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_path_layer as create_path_layer
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_spatial_index as add_spatial_index,
)
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    concat_dataframes as concat_dataframes,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    rename_value_grouper_columns_to_name as rename_value_grouper_columns_to_name,
)
from ecoscope.platform.tasks.transformation import (
    resolve_spatial_feature_groups_for_spatial_groupers as resolve_spatial_feature_groups_for_spatial_groupers,
)
from ecoscope.platform.tasks.transformation import sort_values as sort_values
from ecoscope.platform.tasks.transformation import (
    trend_groupby_columns as trend_groupby_columns,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    subject_obs = (
        task(get_subjectgroup_observations)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("subject_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            include_details=False,
            include_subjectsource_details=False,
            filter="clean",
            **(params.get("subject_obs") or {}),
        )
        .call()
    )

    convert_to_user_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_to_user_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_obs,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_to_user_timezone") or {}),
        )
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    spatial_group_ids = (
        task(extract_spatial_grouper_feature_group_names)
        .validate()
        .set_task_instance_id("spatial_group_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=groupers, **(params.get("spatial_group_ids") or {}))
        .call()
    )

    fetch_spatial_feature_groups = (
        task(get_spatial_features_group)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("fetch_spatial_feature_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name, **(params.get("fetch_spatial_feature_groups") or {})
        )
        .map(argnames=["spatial_features_group_name"], argvalues=spatial_group_ids)
    )

    resolved_groupers = (
        task(resolve_spatial_feature_groups_for_spatial_groupers)
        .validate()
        .set_task_instance_id("resolved_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=groupers,
            spatial_feature_groups=fetch_spatial_feature_groups,
            **(params.get("resolved_groupers") or {}),
        )
        .call()
    )

    subject_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_to_user_timezone,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__subject_subtype",
                "extra__subject__sex",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("subject_reloc") or {}),
        )
        .call()
    )

    subject_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("subject_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=subject_reloc, **(params.get("subject_traj") or {}))
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_traj,
            time_col="segment_start",
            groupers=resolved_groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    traj_add_spatial_index = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("traj_add_spatial_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=traj_add_temporal_index,
            groupers=resolved_groupers,
            **(params.get("traj_add_spatial_index") or {}),
        )
        .call()
    )

    rename_traj_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_traj_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_spatial_index,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__name": "subject_name",
                "extra__subject_subtype": "subject_subtype",
                "extra__sex": "subject_sex",
            },
            raise_if_not_found=True,
            **(params.get("rename_traj_columns") or {}),
        )
        .call()
    )

    classify_traj_speed = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("classify_traj_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_traj_columns,
            input_column_name="speed_kmhr",
            output_column_name="speed_bins",
            classification_options={"scheme": "equal_interval", "k": 6},
            label_options={
                "label_ranges": True,
                "label_decimals": 1,
                "label_suffix": " km/h",
            },
            **(params.get("classify_traj_speed") or {}),
        )
        .call()
    )

    split_subject_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_subject_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=classify_traj_speed,
            groupers=resolved_groupers,
            **(params.get("split_subject_traj_groups") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    sort_traj_speed = (
        task(sort_values)
        .validate()
        .set_task_instance_id("sort_traj_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="speed_bins",
            ascending=True,
            na_position="last",
            **(params.get("sort_traj_speed") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_subject_traj_groups)
    )

    colormap_traj_speed = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("colormap_traj_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="speed_bins",
            output_column_name="speed_bins_colormap",
            colormap=["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"],
            **(params.get("colormap_traj_speed") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sort_traj_speed)
    )

    traj_map_layers = (
        task(create_path_layer)
        .validate()
        .set_task_instance_id("traj_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={"get_color": "speed_bins_colormap"},
            legend={
                "title": "Speed",
                "label_column": "speed_bins",
                "color_column": "speed_bins_colormap",
            },
            **(params.get("traj_map_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=colormap_traj_speed)
    )

    traj_ecomap = (
        task(draw_map)
        .validate()
        .set_task_instance_id("traj_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            legend_style={"placement": "bottom-right"},
            static=False,
            output_type="html",
            title=None,
            max_zoom=20,
            view_state=None,
            **(params.get("traj_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=traj_map_layers)
    )

    ecomap_html_urls = (
        task(persist_text)
        .validate()
        .set_task_instance_id("ecomap_html_urls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("ecomap_html_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=traj_ecomap)
    )

    trend_bucket = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("trend_bucket")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("trend_bucket") or {}))
        .call()
    )

    trend_bucket_column = (
        task(concat_string_vars)
        .validate()
        .set_task_instance_id("trend_bucket_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            values=["TemporalGrouper_", trend_bucket],
            **(params.get("trend_bucket_column") or {}),
        )
        .call()
    )

    traj_add_month_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_month_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_col="segment_start",
            groupers=[{"temporal_index": trend_bucket}],
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_month_index") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_subject_traj_groups)
    )

    traj_named_for_trend = (
        task(rename_value_grouper_columns_to_name)
        .validate()
        .set_task_instance_id("traj_named_for_trend")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=resolved_groupers, **(params.get("traj_named_for_trend") or {})
        )
        .mapvalues(argnames=["df"], argvalues=traj_add_month_index)
    )

    trend_groupby_cols = (
        task(trend_groupby_columns)
        .validate()
        .set_task_instance_id("trend_groupby_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            bucket_column=trend_bucket_column,
            groupers=resolved_groupers,
            **(params.get("trend_groupby_cols") or {}),
        )
        .call()
    )

    speed_trends = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("speed_trends")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            summary_params=[
                {
                    "display_name": "mean_speed_kmhr",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                },
                {
                    "display_name": "period_start",
                    "aggregator": "min",
                    "column": "segment_start",
                    "decimal_places": None,
                },
            ],
            groupby_cols=trend_groupby_cols,
            reset_index=True,
            **(params.get("speed_trends") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=traj_named_for_trend)
    )

    persist_speed_trend_data = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_speed_trend_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            filename_prefix="speed_trends",
            filetypes=["parquet"],
            **(params.get("persist_speed_trend_data") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=speed_trends)
    )

    trend_model = (
        task(set_trend_model)
        .validate()
        .set_task_instance_id("trend_model")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("trend_model") or {}))
        .call()
    )

    trend_fit = (
        task(fit_trend_model)
        .validate()
        .set_task_instance_id("trend_fit")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                is_gamm_trend_model,
            ],
            unpack_depth=1,
        )
        .partial(
            time_column="period_start",
            value_column="mean_speed_kmhr",
            model=trend_model,
            **(params.get("trend_fit") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=speed_trends)
    )

    trend_predictions = (
        task(predict_trend_model)
        .validate()
        .set_task_instance_id("trend_predictions")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_column="time",
            value_column="value",
            time_values=None,
            include_ci=True,
            **(params.get("trend_predictions") or {}),
        )
        .mapvalues(argnames=["model_params"], argvalues=trend_fit)
    )

    speed_trends_combined = (
        task(concat_dataframes)
        .validate()
        .set_task_instance_id("speed_trends_combined")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dfs=speed_trends,
            ensure_columns=["period_start", "mean_speed_kmhr", "name"],
            reset_index=True,
            **(params.get("speed_trends_combined") or {}),
        )
        .call()
    )

    trend_fit_combined = (
        task(fit_trend_model)
        .validate()
        .set_task_instance_id("trend_fit_combined")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                is_not_gamm_trend_model,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=speed_trends_combined,
            time_column="period_start",
            value_column="mean_speed_kmhr",
            model=trend_model,
            **(params.get("trend_fit_combined") or {}),
        )
        .call()
    )

    trend_predictions_gamm = (
        task(predict_trend_model)
        .validate()
        .set_task_instance_id("trend_predictions_gamm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            model_params=trend_fit_combined,
            time_column="period_start",
            value_column="mean_speed_kmhr",
            time_values=None,
            include_ci=True,
            **(params.get("trend_predictions_gamm") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=speed_trends)
    )

    trend_fit_summary_combined = (
        task(get_trend_model_fit_summary)
        .validate()
        .set_task_instance_id("trend_fit_summary_combined")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                is_not_gamm_trend_model,
            ],
            unpack_depth=1,
        )
        .partial(
            model_params=trend_fit_combined,
            model=trend_model,
            **(params.get("trend_fit_summary_combined") or {}),
        )
        .call()
    )

    trend_fit_summary_table_gamm = (
        task(draw_table)
        .validate()
        .set_task_instance_id("trend_fit_summary_table_gamm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=trend_fit_summary_combined,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": False,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("trend_fit_summary_table_gamm") or {}),
        )
        .call()
    )

    persist_fit_summary_table_gamm = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_fit_summary_table_gamm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=trend_fit_summary_table_gamm,
            **(params.get("persist_fit_summary_table_gamm") or {}),
        )
        .call()
    )

    fit_summary_widget_gamm = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("fit_summary_widget_gamm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Trend Model Fit Parameters",
            view=None,
            data=persist_fit_summary_table_gamm,
            **(params.get("fit_summary_widget_gamm") or {}),
        )
        .call()
    )

    trend_predictions_merged = (
        task(groupbykey_passthrough_skip)
        .validate()
        .set_task_instance_id("trend_predictions_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[trend_predictions, trend_predictions_gamm],
            **(params.get("trend_predictions_merged") or {}),
        )
        .call()
    )

    trend_predictions_final = (
        task(concat_dataframes)
        .validate()
        .set_task_instance_id("trend_predictions_final")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            ensure_columns=[],
            reset_index=True,
            **(params.get("trend_predictions_final") or {}),
        )
        .mapvalues(argnames=["dfs"], argvalues=trend_predictions_merged)
    )

    trend_time_cast = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("trend_time_cast")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers={},
            time_col="time",
            cast_to_datetime=True,
            format="mixed",
            **(params.get("trend_time_cast") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=trend_predictions_final)
    )

    persist_trend_data = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_trend_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            filename_prefix="trend_predictions",
            filetypes=["parquet"],
            **(params.get("persist_trend_data") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=trend_time_cast)
    )

    speed_trend_chart = (
        task(draw_historic_timeseries)
        .validate()
        .set_task_instance_id("speed_trend_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            current_value_column="y",
            time_column="time",
            current_value_title="Observed Mean Speed",
            historic_min_column="ci_lower",
            historic_max_column="ci_upper",
            historic_mean_column="predicted",
            historic_mean_title="Trend Estimate",
            historic_band_title="Trend Confidence",
            layout_style={
                "xaxis": {"title": "Time"},
                "yaxis": {"title": "Mean Speed (km/h)"},
            },
            upper_lower_band_style={"mode": "lines", "line": {"color": "green"}},
            historic_mean_style=None,
            current_value_style=None,
            **(params.get("speed_trend_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=trend_time_cast)
    )

    persist_speed_trend_chart = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_speed_trend_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("persist_speed_trend_chart") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=speed_trend_chart)
    )

    map_widget_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("map_widget_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("map_widget_title") or {}))
        .call()
    )

    chart_widget_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("chart_widget_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("chart_widget_title") or {}))
        .call()
    )

    speed_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("speed_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=map_widget_title, **(params.get("speed_map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=ecomap_html_urls)
    )

    grouped_speed_map = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_speed_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(widgets=speed_map_widget, **(params.get("grouped_speed_map") or {}))
        .call()
    )

    speed_trend_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("speed_trend_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=chart_widget_title, **(params.get("speed_trend_widget") or {}))
        .map(argnames=["view", "data"], argvalues=persist_speed_trend_chart)
    )

    grouped_speed_trend = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_speed_trend")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=speed_trend_widget, **(params.get("grouped_speed_trend") or {})
        )
        .call()
    )

    speedmap_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("speedmap_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            time_range=time_range,
            widgets=[grouped_speed_map, grouped_speed_trend, fit_summary_widget_gamm],
            groupers=resolved_groupers,
            **(params.get("speedmap_dashboard") or {}),
        )
        .call()
    )

    return speedmap_dashboard
