# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    extract_spatial_grouper_feature_group_names as extract_spatial_grouper_feature_group_names,
)

get_spatial_features_group = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_core.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_path_layer as create_path_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    add_spatial_index as add_spatial_index,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    resolve_spatial_feature_groups_for_spatial_groupers as resolve_spatial_feature_groups_for_spatial_groupers,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    set_title_var as set_title_var,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "er_client_name": [],
        "subject_obs": ["er_client_name", "time_range"],
        "convert_to_user_timezone": ["subject_obs", "get_timezone"],
        "groupers": [],
        "spatial_group_ids": ["groupers"],
        "fetch_spatial_feature_groups": ["er_client_name", "spatial_group_ids"],
        "resolved_groupers": ["groupers", "fetch_spatial_feature_groups"],
        "subject_reloc": ["convert_to_user_timezone"],
        "subject_traj": ["subject_reloc"],
        "traj_add_temporal_index": ["subject_traj", "resolved_groupers"],
        "traj_add_spatial_index": ["traj_add_temporal_index", "resolved_groupers"],
        "rename_traj_columns": ["traj_add_spatial_index"],
        "classify_traj_speed": ["rename_traj_columns"],
        "split_subject_traj_groups": ["classify_traj_speed", "resolved_groupers"],
        "base_map_defs": [],
        "sort_traj_speed": ["split_subject_traj_groups"],
        "colormap_traj_speed": ["sort_traj_speed"],
        "traj_map_layers": ["colormap_traj_speed"],
        "traj_ecomap": ["base_map_defs", "traj_map_layers"],
        "ecomap_html_urls": ["traj_ecomap"],
        "traj_add_month_index": ["split_subject_traj_groups"],
        "speed_trends": ["traj_add_month_index"],
        "persist_speed_trend_data": ["speed_trends"],
        "gamm_model": ["speed_trends"],
        "trend_predictions": ["gamm_model"],
        "trend_time_cast": ["trend_predictions"],
        "persist_trend_data": ["trend_time_cast"],
        "speed_trend_chart": ["trend_time_cast"],
        "persist_speed_trend_chart": ["speed_trend_chart"],
        "map_widget_title": [],
        "chart_widget_title": [],
        "speed_map_widget": ["map_widget_title", "ecomap_html_urls"],
        "grouped_speed_map": ["speed_map_widget"],
        "speed_trend_widget": ["chart_widget_title", "persist_speed_trend_chart"],
        "grouped_speed_trend": ["speed_trend_widget"],
        "speedmap_dashboard": [
            "workflow_details",
            "time_range",
            "grouped_speed_map",
            "grouped_speed_trend",
            "resolved_groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "subject_obs": Node(
            async_task=get_subjectgroup_observations.validate()
            .set_task_instance_id("subject_obs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "raise_on_empty": False,
                "include_details": False,
                "include_subjectsource_details": False,
                "filter": "clean",
            }
            | (params_dict.get("subject_obs") or {}),
            method="call",
        ),
        "convert_to_user_timezone": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_to_user_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("subject_obs"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "fixtime",
                ],
            }
            | (params_dict.get("convert_to_user_timezone") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "spatial_group_ids": Node(
            async_task=extract_spatial_grouper_feature_group_names.validate()
            .set_task_instance_id("spatial_group_ids")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("spatial_group_ids") or {}),
            method="call",
        ),
        "fetch_spatial_feature_groups": Node(
            async_task=get_spatial_features_group.validate()
            .set_task_instance_id("fetch_spatial_feature_groups")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
            }
            | (params_dict.get("fetch_spatial_feature_groups") or {}),
            method="map",
            kwargs={
                "argnames": ["spatial_features_group_name"],
                "argvalues": DependsOn("spatial_group_ids"),
            },
        ),
        "resolved_groupers": Node(
            async_task=resolve_spatial_feature_groups_for_spatial_groupers.validate()
            .set_task_instance_id("resolved_groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupers": DependsOn("groupers"),
                "spatial_feature_groups": DependsOn("fetch_spatial_feature_groups"),
            }
            | (params_dict.get("resolved_groupers") or {}),
            method="call",
        ),
        "subject_reloc": Node(
            async_task=process_relocations.validate()
            .set_task_instance_id("subject_reloc")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "observations": DependsOn("convert_to_user_timezone"),
                "relocs_columns": [
                    "groupby_col",
                    "fixtime",
                    "junk_status",
                    "geometry",
                    "extra__subject__name",
                    "extra__subject__subject_subtype",
                    "extra__subject__sex",
                ],
                "filter_point_coords": [
                    {
                        "x": 180.0,
                        "y": 90.0,
                    },
                    {
                        "x": 0.0,
                        "y": 0.0,
                    },
                    {
                        "x": 1.0,
                        "y": 1.0,
                    },
                ],
            }
            | (params_dict.get("subject_reloc") or {}),
            method="call",
        ),
        "subject_traj": Node(
            async_task=relocations_to_trajectory.validate()
            .set_task_instance_id("subject_traj")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("subject_reloc"),
            }
            | (params_dict.get("subject_traj") or {}),
            method="call",
        ),
        "traj_add_temporal_index": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("traj_add_temporal_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("subject_traj"),
                "time_col": "segment_start",
                "groupers": DependsOn("resolved_groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("traj_add_temporal_index") or {}),
            method="call",
        ),
        "traj_add_spatial_index": Node(
            async_task=add_spatial_index.validate()
            .set_task_instance_id("traj_add_spatial_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("traj_add_temporal_index"),
                "groupers": DependsOn("resolved_groupers"),
            }
            | (params_dict.get("traj_add_spatial_index") or {}),
            method="call",
        ),
        "rename_traj_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_traj_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("traj_add_spatial_index"),
                "rename_columns": {
                    "extra__name": "subject_name",
                    "extra__subject_subtype": "subject_subtype",
                    "extra__sex": "subject_sex",
                },
                "raise_if_not_found": True,
            }
            | (params_dict.get("rename_traj_columns") or {}),
            method="call",
        ),
        "classify_traj_speed": Node(
            async_task=apply_classification.validate()
            .set_task_instance_id("classify_traj_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_traj_columns"),
                "input_column_name": "speed_kmhr",
                "output_column_name": "speed_bins",
                "classification_options": {
                    "scheme": "equal_interval",
                    "k": 6,
                },
                "label_options": {
                    "label_ranges": True,
                    "label_decimals": 1,
                    "label_suffix": " km/h",
                },
            }
            | (params_dict.get("classify_traj_speed") or {}),
            method="call",
        ),
        "split_subject_traj_groups": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_subject_traj_groups")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("classify_traj_speed"),
                "groupers": DependsOn("resolved_groupers"),
            }
            | (params_dict.get("split_subject_traj_groups") or {}),
            method="call",
        ),
        "base_map_defs": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "sort_traj_speed": Node(
            async_task=sort_values.validate()
            .set_task_instance_id("sort_traj_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "speed_bins",
                "ascending": True,
                "na_position": "last",
            }
            | (params_dict.get("sort_traj_speed") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "colormap_traj_speed": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("colormap_traj_speed")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "input_column_name": "speed_bins",
                "output_column_name": "speed_bins_colormap",
                "colormap": [
                    "#1a9850",
                    "#91cf60",
                    "#d9ef8b",
                    "#fee08b",
                    "#fc8d59",
                    "#d73027",
                ],
            }
            | (params_dict.get("colormap_traj_speed") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("sort_traj_speed"),
            },
        ),
        "traj_map_layers": Node(
            async_task=create_path_layer.validate()
            .set_task_instance_id("traj_map_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "get_color": "speed_bins_colormap",
                },
                "legend": {
                    "title": "Speed",
                    "label_column": "speed_bins",
                    "color_column": "speed_bins_colormap",
                },
            }
            | (params_dict.get("traj_map_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("colormap_traj_speed"),
            },
        ),
        "traj_ecomap": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("traj_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("base_map_defs"),
                "legend_style": {
                    "placement": "bottom-right",
                },
                "static": False,
                "title": None,
                "max_zoom": 20,
                "view_state": None,
            }
            | (params_dict.get("traj_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("traj_map_layers"),
            },
        ),
        "ecomap_html_urls": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("ecomap_html_urls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("ecomap_html_urls") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("traj_ecomap"),
            },
        ),
        "traj_add_month_index": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("traj_add_month_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_col": "segment_start",
                "groupers": [
                    {
                        "temporal_index": "%Y-%m",
                    },
                ],
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("traj_add_month_index") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "speed_trends": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("speed_trends")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "summary_params": [
                    {
                        "display_name": "mean_speed_kmhr",
                        "aggregator": "mean",
                        "column": "speed_kmhr",
                    },
                    {
                        "display_name": "period_start",
                        "aggregator": "min",
                        "column": "segment_start",
                        "decimal_places": None,
                    },
                ],
                "groupby_cols": [
                    "TemporalGrouper_%Y-%m",
                ],
                "reset_index": True,
            }
            | (params_dict.get("speed_trends") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("traj_add_month_index"),
            },
        ),
        "persist_speed_trend_data": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_speed_trend_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "sanitize": True,
                "filename_prefix": "speed_trends",
                "filetypes": [
                    "parquet",
                ],
            }
            | (params_dict.get("persist_speed_trend_data") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("speed_trends"),
            },
        ),
        "gamm_model": Node(
            async_task=fit_gamm_model.validate()
            .set_task_instance_id("gamm_model")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_column": "period_start",
                "value_column": "mean_speed_kmhr",
                "lower_bound": None,
                "upper_bound": None,
                "optimize_alpha": False,
                "alpha": 1.0,
            }
            | (params_dict.get("gamm_model") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("speed_trends"),
            },
        ),
        "trend_predictions": Node(
            async_task=predict_gamm_trends.validate()
            .set_task_instance_id("trend_predictions")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_values": None,
                "include_ci": True,
            }
            | (params_dict.get("trend_predictions") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["model_params"],
                "argvalues": DependsOn("gamm_model"),
            },
        ),
        "trend_time_cast": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("trend_time_cast")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_col": "time",
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("trend_time_cast") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("trend_predictions"),
            },
        ),
        "persist_trend_data": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_trend_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "sanitize": True,
                "filename_prefix": "trend_predictions",
                "filetypes": [
                    "parquet",
                ],
            }
            | (params_dict.get("persist_trend_data") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("trend_time_cast"),
            },
        ),
        "speed_trend_chart": Node(
            async_task=draw_historic_timeseries.validate()
            .set_task_instance_id("speed_trend_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "current_value_column": "y",
                "time_column": "time",
                "current_value_title": "Observed Mean Speed",
                "historic_min_column": "ci_lower",
                "historic_max_column": "ci_upper",
                "historic_mean_column": "predicted",
                "historic_mean_title": "Trend Estimate",
                "historic_band_title": "Trend Confidence",
                "layout_style": {
                    "xaxis": {
                        "title": "Time",
                    },
                    "yaxis": {
                        "title": "Mean Speed (km/h)",
                    },
                },
                "upper_lower_band_style": {
                    "mode": "lines",
                    "line": {
                        "color": "green",
                    },
                },
                "historic_mean_style": None,
                "current_value_style": None,
            }
            | (params_dict.get("speed_trend_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("trend_time_cast"),
            },
        ),
        "persist_speed_trend_chart": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_speed_trend_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_speed_trend_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("speed_trend_chart"),
            },
        ),
        "map_widget_title": Node(
            async_task=set_title_var.validate()
            .set_task_instance_id("map_widget_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("map_widget_title") or {}),
            method="call",
        ),
        "chart_widget_title": Node(
            async_task=set_title_var.validate()
            .set_task_instance_id("chart_widget_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("chart_widget_title") or {}),
            method="call",
        ),
        "speed_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("speed_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("map_widget_title"),
            }
            | (params_dict.get("speed_map_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("ecomap_html_urls"),
            },
        ),
        "grouped_speed_map": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_speed_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("speed_map_widget"),
            }
            | (params_dict.get("grouped_speed_map") or {}),
            method="call",
        ),
        "speed_trend_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("speed_trend_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("chart_widget_title"),
            }
            | (params_dict.get("speed_trend_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_speed_trend_chart"),
            },
        ),
        "grouped_speed_trend": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_speed_trend")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("speed_trend_widget"),
            }
            | (params_dict.get("grouped_speed_trend") or {}),
            method="call",
        ),
        "speedmap_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("speedmap_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "widgets": [
                    DependsOn("grouped_speed_map"),
                    DependsOn("grouped_speed_trend"),
                ],
                "groupers": DependsOn("resolved_groupers"),
            }
            | (params_dict.get("speedmap_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
