# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class SubjectObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_group_name: str = Field(
        ...,
        description="⚠️ The use of a group with mixed subtypes could lead to unexpected results",
        title="Subject Group Name",
    )


class SubjectGroup(BaseModel):
    subject_obs: SubjectObs | None = Field(None, title="")


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: constr(pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)") | None = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: int | None = Field(
        20,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: int | None = Field(
        0,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMapDefs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: list[BaseMaps | BaseMaps1 | BaseMaps2 | BaseMaps3 | BaseMaps4 | BaseMaps5 | BaseMaps6] | None = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
                "max_zoom": 20,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
                "max_zoom": 20,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class Metric(str, Enum):
    AIC = "AIC"
    BIC = "BIC"
    Euclidean = "Euclidean"
    MSE = "MSE"
    R_Squared = "R-Squared"


class Family(str, Enum):
    Gaussian = "Gaussian"
    Poisson = "Poisson"
    Binomial = "Binomial"


class GammModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alpha: float | None = Field(
        1.0,
        description="Fixed smoothing parameter, used only when Optimize Alpha is off.",
        title="Alpha",
    )
    optimize_alpha: bool | None = Field(
        False,
        description='Automatically search for the best smoothing parameter. The automatic search can fail ("Perfect separation detected") on groups with very few monthly data points, so this defaults to off with a fixed Alpha value instead; turn it on for a data-driven fit on larger groups.',
        title="Optimize Alpha",
    )
    metric: Metric | None = Field(
        "AIC", description="Metric for optimization", title="Metric"
    )
    degree_of_freedom: int | None = Field(
        3,
        description="Degrees of freedom for the trend spline. Lower this if the fit fails (e.g. for a group with few monthly data points); raise it for a smoother fit on longer time series with more data points. Must be greater than Degree.",
        title="Degree Of Freedom",
    )
    degree: int | None = Field(
        2,
        description="Degree of the trend spline (2 = quadratic). Lower values fit more reliably on groups with few monthly data points; degree must be at least 2 for the smoothing penalty to be computed.",
        title="Degree",
    )
    family: Family | None = Field(
        "Gaussian", description="Distribution family for GLM", title="Family"
    )


class TrendAnalysis(BaseModel):
    gamm_model: GammModel | None = Field(None, title="")


class MapWidgetTitle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str = Field(
        ..., description="Title displayed on the speed map.", title="Map Title"
    )


class ChartWidgetTitle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str = Field(
        ...,
        description="Title displayed on the GAMM speed trend chart.",
        title="Trend Chart Title",
    )


class Dashboard(BaseModel):
    map_widget_title: MapWidgetTitle | None = Field(None, title="")
    chart_widget_title: ChartWidgetTitle | None = Field(None, title="")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: confloat(ge=0.001) | None = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: confloat(gt=0.001) | None = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: confloat(ge=1.0) | None = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: confloat(gt=1.0) | None = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: confloat(gt=0.001) | None = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: confloat(gt=0.001) | None = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class CustomLabels(BaseModel):
    label_prefix: str | None = Field("", title="Label Prefix")
    label_suffix: str | None = Field("", title="Label Suffix")
    labels: list[str] = Field(..., title="Labels")


class DefaultLabels(BaseModel):
    label_prefix: str | None = Field("", title="Label Prefix")
    label_suffix: str | None = Field(" km/h", title="Label Suffix")
    label_ranges: bool | None = Field(True, title="Label Ranges")
    label_decimals: int | None = Field(1, title="Label Decimals")


class ViewState(BaseModel):
    longitude: confloat(ge=-180.0, le=180.0) | None = Field(0, title="Longitude")
    latitude: confloat(ge=-90.0, le=90.0) | None = Field(0, title="Latitude")
    zoom: confloat(ge=0.0, le=20.0) | None = Field(0, title="Zoom")
    pitch: confloat(ge=0.0, le=60.0) | None = Field(0, title="Pitch")
    bearing: confloat(le=360.0) | None = Field(0, title="Bearing")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(
        ..., description="Start of the movement analysis period.", title="Since"
    )
    until: datetime = Field(
        ..., description="End of the movement analysis period.", title="Until"
    )
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: list[TemporalGrouper | ValueGrouper] | None = Field(
        None,
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class GroupData(BaseModel):
    groupers: Groupers | None = Field(None, title="")


class SubjectTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: TrajectorySegmentFilter | None = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class ClassifyTrajSpeed(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label_options: DefaultLabels | CustomLabels | None = Field(
        None,
        description="Optional specification or formatting of classification values.",
        title="Label Options",
    )


class TrajEcomap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    view_state: ViewState | None = Field(
        default_factory=lambda: ViewState.model_validate(
            {"longitude": 0, "latitude": 0, "zoom": 0, "pitch": 0, "bearing": 0}
        ),
        description="Manually set the view state of the map.",
        title="View State",
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    er_client_name: ErClientName | None = Field(None, title="Data Source")
    Subject_Group: SubjectGroup | None = Field(
        None,
        alias="Subject Group",
        description="Choose the EarthRanger subject group to map and analyze.",
    )
    Group_Data: GroupData | None = Field(
        None,
        alias="Group Data",
        description="Optionally group the data by subject, time period, or spatial feature group.",
    )
    subject_traj: SubjectTraj | None = Field(
        None, title="Convert Relocations to Trajectory"
    )
    classify_traj_speed: ClassifyTrajSpeed | None = Field(None, title="")
    base_map_defs: BaseMapDefs | None = Field(None, title="Base Maps")
    traj_ecomap: TrajEcomap | None = Field(None, title="")
    Trend_Analysis: TrendAnalysis | None = Field(
        None,
        alias="Trend Analysis",
        description="Configure the GAM trend fitting parameters for mean speed over time.",
    )
    Dashboard_1: Dashboard | None = Field(
        None, alias="Dashboard", description="Configure the dashboard output titles."
    )
